### ISSUE TITLE
`encoding` property isn't expected?

### ISSUE THREAD

**Issue by toohsk** [treasure-data/pandas-td#14]
HI, devs member!
Our team is using `pandas-td` in the ETL batch. 
Thank you very much for developing a useful tool!

By the way, the below error was raised when I execute `pd_td.read_td()` method.

```
Traceback (most recent call last):
...
  File "venv/lib/python3.6/site-packages/pandas_td/td.py", line 269, in __iter__
    for record in msgpack.Unpacker(self, encoding='utf-8'):
  File "msgpack/_unpacker.pyx", line 317, in msgpack._cmsgpack.Unpacker.__init__
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

And when I ignored the encoding argument, it worked as expected.
Probably this error is related to msgpack library update.

I think there a few approaches to avoid this.

1. define msgpack version in setup.py
2. remove `encoding` argument from `pandas-td.td.ResultProxy.read_td()`

How do you think?

**Comment by chezou** [comment]
@toohsk thanks for letting us know. Unfortunately, pandas-td is no longer maintained. Could you try pytd instead? It's pandas-td successor and should be compatible.
https://pytd-doc.readthedocs.io/en/latest/#how-to-replace-pandas-td

**Comment by toohsk** [comment]
@chezou 
Thanks for noticing!
